export const MESSAGE = {
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    OTP_REQUIRED: 'OTP_REQUIRED',
    OK: 'OK',
    SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
    OTP_EXIRED: "OTP_EXIRED",
    MISSING_ACCESS_TOKEN: "MISSING_ACCESS_TOKEN",
    PAYMENT_ALREADY_PROCESSED: "PAYMENT_ALREADY_PROCESSED"
}